### ISSUE TITLE
Terminbuchung statt Verschiebung

### ISSUE THREAD

**Issue by jens0r94** [timderspieler/Saarland-Impftermin-Bot#2]
Hallo,

können mit dem Programm auch neue Termine gebucht werden, also ohne das bereits eine Terminbuchung besteht?

Was passiert nachdem das Programm einen Termin gefunden hat? Muss man diesen noch manuell bestätigen oder bucht das Programm automatisch den freien Termin?

Vorab vielen Dank.

**Comment by timderspieler** [comment]
Hallo,

Sie können mit dem Programm auch einen Termin buchen ohne das Sie zuvor einen solchen zugewiesen bekommen haben.

Nachdem ein Termin gefunden wurde bekommen Sie ein Popup welches Sie auffordert das Browserfenster zu öffnen, welches das Programm generiert hat.

Im Browser geben sie dann ihre Handynummer / E-Mail Adresse ein, mit welcher sie sich registriert haben. (Außer sie haben die Option "Auto-Login" ausgewählt). Danach erhalten Sie einen Code per SMS / E-Mail. Tragen sie diesen ein und melden sie sich an.
Abschließend können sie den gefundenen Termin buchen.

Es sei allerdings angemerkt, dass wenig Zeit vergehen darf zwischen "Termin wurde gefunden" und "Ich melde mich an". Lassen sie sich am besten den Code per SMS senden (Dies hat sich im Praxistest bewährt gemacht 😆 ).

Viel Glück bei der "Terminsuche" :)

**Comment by jens0r94** [comment]
Hallo,

vielen Dank für die schnelle Hilfe. Dann versuche ich mein Glück!

**Comment by jens0r94** [comment]
Besteht auch die Möglichkeit sich vorab einzuloggen, damit man diesen Schritt mit dem Code überspringt? Bei der "manuellen" Terminsuche kann man sich bereits vorher einloggen und dann muss man "nur" noch auf einen freien Termin drücken, falls es einen gibt.

**Comment by timderspieler** [comment]
Bei der Buchung kurzfristig freier Termine ist dies leider nicht möglich.

**Comment by jens0r94** [comment]
Wie wenig Zeit darf zwischen "Termin wurde gefunden" und "Ich melde mich an" denn vergehen? Wird der Termin für eine gewisse Zeit geblockt?
Hintergrund ist: Ich versuche für eine andere Person zu buchen, habe also keinen direkten Zugang zum Handy der Person.

**Comment by timderspieler** [comment]
Der Termin wird ca. 2-3 Minuten für sie geblockt. Es gilt aber: Desto schneller, desto besser.

**Comment by jens0r94** [comment]
Vielen Dank für die schnelle Antwort.

**Comment by timderspieler** [comment]
Hallo @jens0r94 ,

haben Sie schon einen Termin gefunden? :)

**Comment by jens0r94** [comment]
Leider konnte gestern kein Termin in einem Zeitraum von ca. 1 1/2 Stunden gefunden werden. Aber die Person hat jetzt doch über einen Hausarzt einen Termin bekommen.
Trotzdem vielen Dank für die schnelle Unterstützung und generell für die Bereitstellung des Tools. Funktioniert genau so wie es soll. Nur ich denke aktuell ist die Nachfrage sehr, sehr hoch. Hätte die Person keinen Termin bekommen, hätte ich mit Sicherheit heute einen Termin dank des Tools bekommen ;)

**Comment by timderspieler** [comment]
Okay danke für die Rückmeldung.

Freut mich das das Tool gut angekommen ist. Hoffentlich kann es auch in Zukunft weiterhelfen.

Bleiben Sie gesund! 

Gruß
Tim
